### ISSUE TITLE
Angular 2 cron editor

### ISSUE THREAD

**Issue by bindu1552** [claudiuconstantin/cron-editor#3] opened 2017-09-21 11:28 UTC
After integrating the changes i'm getting the below error:
] ERROR in c:/NEERCompliance/complianceapp/ComplianceApp.Web/client
-app/app/control-administration/schedule/cron-editor/cron-editor.comp
onent.ts (8,15): Ca

**Comment by claudiuconstantin** [comment] 2017-09-21 12:58
Please post the entire error log and call stack

**Comment by claudiuconstantin** [comment] 2017-09-22 06:26
Duplicate of #2, let's continue the discussion there

**Closed as completed by claudiuconstantin** 2017-09-22 06:26 UTC
Labels: duplicate, invalid
