### ISSUE TITLE
ERROR in CronEditorModule is not an NgModule

### ISSUE THREAD

**Issue by ravidannani** [claudiuconstantin/cron-editor#2] opened 2017-09-21 08:07 UTC
First of all, Thank You for making it available for angular2.

I have below issue after installing the package and start the application.

"ERROR in CronEditorModule is not an NgModule"

Could you please help me.

**Comment by claudiuconstantin** [comment] 2017-09-21 08:29
Please explain exactly what are you trying to do, which commands do you run? Attaching your `packages.json` file would be really helpful

**Comment by ravidannani** [comment] 2017-09-21 09:52
Thanks for your quick response. 

Below are the steps that I followed
1. Install the package $ npm i cron-editor -S
2. Imported into module file.
3. Added code in html .
<cron-editor [(cron)]="cronExpression"></cron-editor>
4. Finally ran the app. 
 And getting the issue.

Attached is my package.json. 

Please let me know if I went wrong.



[package1.txt](https://github.com/claudiuconstantin/cron-editor/files/1320703/package1.txt)

**Comment by claudiuconstantin** [comment] 2017-09-21 11:10
The usage should look something like this:
```
import { NgModule } from "@angular/core";
import { CronEditorModule } from "cron-editor/cron-editor";

@NgModule({
    imports: [CronEditorModule]
})

export class ExampleModule {
}
```

**Comment by ravidannani** [comment] 2017-09-21 11:28
Yes, same thing I did.. But getting issue.

**Comment by claudiuconstantin** [comment] 2017-09-21 13:01
Can you paste a more detailed error/call stack? Also do check out this [thread](https://github.com/angular/angular-cli/issues/3426), it might be an angular/cli issue

**Comment by ravidannani** [comment] 2017-09-21 13:06
Actually I was following the same steps that you provided (even mentioned above). But getting this issue. I tried in multiple projects to see. But getting the same issue.

I have attached the console log issue. Please see
![cron-issue](https://user-images.githubusercontent.com/27359086/30697179-adb79748-9efb-11e7-9732-4804a095b9e6.png)

**Comment by claudiuconstantin** [comment] 2017-09-21 13:34
This type of error can happen when you're incorrectly using the `imports`/`declarations`/`providers ` sections in your `NgModule` (examples [here](https://github.com/angular/angular/issues/15890)). Can you attach your "ControlAdministrationModule"?

**Comment by bindu1552** [comment] 2017-09-22 06:14
[control-administration (3).zip](https://github.com/claudiuconstantin/cron-editor/files/1323584/control-administration.3.zip)

attached is the control administration and package.json 
below i'm adding the [error:]
![image](https://user-images.githubusercontent.com/20336131/30731502-5bb379fe-9f8b-11e7-9e71-8a2cd5616ab8.png)

**Comment by bindu1552** [comment] 2017-09-22 08:50
After integrating the code .I have added cron-editor in provider to work to resolve the ngmodule issue

now i'm getting the below error.

![image](https://user-images.githubusercontent.com/20336131/30736601-0545cb6a-9fa1-11e7-9b79-a57a48673086.png)

**Comment by ravidannani** [comment] 2017-09-25 06:40
Hi brother,

After I have followed all the steps mentioned in the below link,
https://github.com/claudiuconstantin/cron-editor

Getting the below issue.

![image](https://user-images.githubusercontent.com/27359086/30795297-7a27bfc4-a1ea-11e7-9e27-f4eed678f4df.png)

Could you please tell me if something i missed. Thanks in advance for your great help.

**Comment by claudiuconstantin** [comment] 2017-09-26 15:02
Can you check out the new `0.1.6` release and see if the issue is still reproducing?

**Comment by henrikcs** [comment] 2017-09-27 12:13
Hi!
I also got the error "CronEditorModule is not an NgModule" when running `npm run start`:
````
ERROR in Error: CronEditorModule is not an NgModule
    at _getNgModuleMetadata (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109
:26)
    at C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128
:10)
    at Object.listLazyRoutesOfModule (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtoo
ls_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\henri\Documents\MEGA\Arbeit\Datea\Datea_git\LiquidityPlanner\src\main\webapp\node_modules\@ngtools\webpack\src\plugi
n.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.
````

I was able to resolve this issue by adding `@NgModule()` on top of the `cron-editor.module.d.ts`-File under `/node_modules/cron-editor/components/cron-editor`. It now looks like this:

```
import { NgModule } from "@angular/core";

@NgModule()
export declare class CronEditorModule {
}
```

However, when trying to run an AOT-Compilation, I am getting the following error:

```
ERROR in Error: Template parse errors:
Can't bind to 'cron' since it isn't a known property of 'cron-editor'.
1. If 'cron-editor' is an Angular component and it has 'cron' input, then verify that it is part of this module.
2. If 'cron-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
</ul>

<cron-editor [ERROR ->][(cron)]="cronExpression" [options]="cronOptions"></cron-editor>
"): ng:///C:/Users/henri/Desktop/temp/cron-test/src/app/app.component.html@20:13
Can't bind to 'options' since it isn't a known property of 'cron-editor'.
1. If 'cron-editor' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'cron-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
</ul>

<cron-editor [(cron)]="cronExpression" [ERROR ->][options]="cronOptions"></cron-editor>
"): ng:///C:/Users/henri/Desktop/temp/cron-test/src/app/app.component.html@20:39
'cron-editor' is not a known element:
1. If 'cron-editor' is an Angular component, then verify that it is part of this module.
2. If 'cron-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</ul>

[ERROR ->]<cron-editor [(cron)]="cronExpression" [options]="cronOptions"></cron-editor>
"): ng:///C:/Users/henri/Desktop/temp/cron-test/src/app/app.component.html@20:0
    at Error (native)
    at syntaxError (C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at TemplateParser.parse (C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12967:19)
    at AotCompiler._compileComponent (C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:24189:39)
    at C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:24070:55
    at Array.forEach (native)
    at AotCompiler._compileImplFile (C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:24053:20)
    at C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:23964:87
    at Array.map (native)
    at AotCompiler.emitAllImpls (C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler\bundles\compiler.umd.js:23964:52)
    at CodeGenerator.emit (C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler-cli\src\codegen.js:42:46)
    at C:\Users\henri\Desktop\temp\cron-test\node_modules\@angular\compiler-cli\src\codegen.js:33:61
    at process._tickCallback (internal/process/next_tick.js:109:7)
```


I am using the 0.1.6 version of your project. 

`npm version` returns the following:
```
npm version
{ 'cron-test': '0.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.3',
  openssl: '1.0.2l',
  uv: '1.11.0',
  v8: '5.1.281.107',
  zlib: '1.2.11' }
```

`ng-version` returns the following:
```
@angular/cli: 1.4.2
node: 6.11.3
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```

**Comment by MichaelMalony** [comment] 2017-10-10 17:20
I'm seeing the same thing.

Steps to reproduce:

- Create new project: ng new my-app
- Add cron-editor: npm i cron-editor -S
- Update AppModule:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { CronEditorModule } from "cron-editor/cron-editor";
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
	CronEditorModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
- Run: ng serve --open

Error:

> ** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 8/9 modules 1 active ...ode_modules\style-loader\addDate: 2017-10-10T16:08:15.216Z
Hash: fdbd5bb6930b28207d29
Time: 2075ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.06 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 338 kB [initial] [rendered]
ERROR in Error: CronEditorModule is not an NgModule
    at _getNgModuleMetadata (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at D:\User Files\mlm\Desktop\test2\my-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\User Files\mlm\Desktop\test2\my-app\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
webpack: Failed to compile.

ng version output:
```
@angular/cli: 1.4.5
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```

**Comment by MichaelMalony** [comment] 2017-10-10 18:22
Also tried this with no luck:
`npm install https://github.com/claudiuconstantin/cron-editor.git --save`

However, if I pull down the repo and run the sample works OK.

**Comment by claudiuconstantin** [comment] 2017-10-11 06:40
There seems to be a problem with the way we pack the module. I'll look into it

**Comment by xcorpio** [comment] 2017-10-16 08:39
Same issue

**Comment by User3290** [comment] 2017-10-20 15:59
We have the same issue. Are you going to solve this problem in closest time? 1 month ago topic has been opened and nothing done...

**Comment by claudiuconstantin** [comment] 2017-10-23 10:30
I was able to reproduce the steps from @MichaelMalony (thanks!) - it seems that the module is not correctly packed for `angular-cli` usage. We're not using cli, but manual `webpack` in production and so we were able to successfully use cron-editor npm package in that scenario. I will investigate this.

For your concerns, @User3290, calm you're entitlement. I'm maintaining this open-source component in my little spare-time and I'm trying to make it useful for the community as my time allows. I'll gladly accept practical suggestions. Follow this thread for news on the topic

**Comment by camposfyi** [comment] 2017-11-02 18:45
I'm getting the same issue:
ERROR in Error: CronEditorModule is not an NgModule

**Comment by bindu1552** [comment] 2017-11-02 18:48
instead of giving npm reference ..add the cron editor in project and refer the project folder it may resolve the issue.

**Comment by thudont** [comment] 2017-11-14 07:58
Hi, 
I'm using cron-editor v0.1.6 for my Angular2 project + node v6.0.38. When I load page, I get this error: 
![image](https://user-images.githubusercontent.com/28382702/32764025-ee862848-c935-11e7-9a10-375cb1c56def.png)
I also added the cron editor in project and refer the project folder, but this error still occur.
Could you please help me?

**Comment by rajeshkdev** [comment] 2017-12-08 10:34
I Made it Work, After spending few hours.

I have uploaded the POC in GitHub as a sample. https://github.com/rajeshkdev/Angular-4-Cron-Editor-with-Bootstrap-3.3.7. Just Download and do `npm install` from the project root directory.

**OR**

I followed these steps in order to get it work, I'm using **[Angular 4+ with CLI](https://cli.angular.io/)** + [Bootstrap 3.3.7](http://getbootstrap.com/docs/3.3/getting-started/).

Created [Angular 4+](https://angular.io/guide/quickstart) Project using the following command in the CLI:

> ng new CheckGeek

**Install the npm packages:**

1. Install the Cron Editor Package

> npm i cron-editor -S

2. Install the Bootstrap Package: 

> npm install bootstrap@3.3.7

In order to get the Look and Feel, Alter your **.angular-cli.json** file the "style" property must load the Bootstrap Css. It should look like below.,

```
"styles": [
            "../node_modules/bootstrap/dist/css/bootstrap.min.css",
            "styles.css"
        ],
```

I have updated the `app.component.html` and its looks like below.,

**app.component.html**
```
<div style="text-align:center">
    <h1>Rajesh updated - Angular 2+ Cron expression editor</h1>
</div>

<hr>

<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <cron-editor [(cron)]="cronExpression" [disabled]="isCronDisabled" [(options)]="cronOptions">Cron here...</cron-editor>

        <div class="row alert alert-info" style="text-align:center">
            <h3>
                <b>{{cronExpression}}</b>
            </h3>
            <hr/>
        </div>
    </div>
    <div class="col-sm-2"></div>
</div>
```

I have updated the `app.component.ts` the relevant model property declarations are available here with it.

**app.component.ts**
```
import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { CronOptions } from 'cron-editor/cron-editor';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  public cronExpression = '4 3 2 12 1/1 ? *';
  public isCronDisabled = false;
  public cronOptions: CronOptions = {
    formInputClass: 'form-control cron-editor-input',
    formSelectClass: 'form-control cron-editor-select',
    formRadioClass: 'cron-editor-radio',
    formCheckboxClass: 'cron-editor-checkbox',

    defaultTime: '10:00:00',

    hideMinutesTab: false,
    hideHourlyTab: false,
    hideDailyTab: false,
    hideWeeklyTab: false,
    hideMonthlyTab: false,
    hideYearlyTab: false,
    hideAdvancedTab: true,
    use24HourTime: true,
    hideSeconds: false
  };
}
```

I have updated the `CronEditorModule ` imports in `app.module.ts`

**app.module.ts**

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { CronEditorModule } from 'cron-editor/cron-editor';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CronEditorModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule { }
```

> As i followed @henrikcs comments, i was able to solve the "CronEditorModule is not an NgModule" when running `npm start`.

I was able to resolve this issue by adding @NgModule() on top of the `cron-editor.module.d.ts` File under `/node_modules/cron-editor/components/cron-editor`. It now looks like this:

```
import { NgModule } from "@angular/core";

@NgModule()
export declare class CronEditorModule {
}
```

And finally got the Results., Hope this helps.,

**Comment by amolpowar** [comment] 2018-01-03 18:43
After following @henrikcs suggestion I could make it work

import { NgModule } from "@angular/core";

@NgModule()
export declare class CronEditorModule {
}

Do you have any plans for committing the changes?

**Comment by KasturiHadap** [comment] 2018-01-16 09:13
Please tell if any solution exist for same issue. I have used the above solution suggested by amolpowar, but this gives error while ng build -prod.

**Comment by FreezeSoul** [comment] 2018-01-30 13:55
same error in my project. at last , i copy the src into my project ....

**Comment by claudiuconstantin** [comment] 2018-01-30 14:11
Sorry for the long waiting time, I got some busy months lately. I'll try to figure this out and come with a fix soon. Thanks for all the info!

**Comment by layely2** [comment] 2018-02-13 15:35
Any update ? 
Using manual webpack, I got the same error ... and looking forward to a fix.
Suggested workarround above works but is far from good practices !

**Comment by spmanjunath** [comment] 2018-02-27 09:01
I was getting "ERROR in Error: CronEditorModule is not an NgModule" and this was resolved by adding @NgModule to **cron-editor.module.d.ts** file.  With this i am able to successfully run the application.  However, building the application with --aot flag results in the following error,

_ERROR in : Can't bind to 'cron' since it isn't a known property of 'cron-editor'.
1. If 'cron-editor' is an Angular component and it has 'cron' input, then verify that it is part of this module.2. If 'cron-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
      <cron-editor [ERROR ->][(cron)]="cronExpression" [disabled]="isCronDisabled" [(options)]="cronOptions">Cron here...</cron-ed")
: Can't bind to 'disabled' since it isn't a known property of 'cron-editor'.
1. If 'cron-editor' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'cron-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <div class="col-sm-2"></div>
  <div class="col-sm-8">
      <cron-editor [(cron)]="cronExpression" [ERROR ->][disabled]="isCronDisabled" [(options)]="cronOptions">Cron here...</cron-editor>

      <div class="r")_

Has anyone able to resolve this error, any workaround to fix this issue?

**Comment by ubiqs** [comment] 2018-05-07 13:37
I am also getting the same issue as
spmanjunath.

Will this component work with AOT ?
Some workaround that can be done ?

**Comment by PheelaV** [comment] 2018-05-27 16:59
@spmanjunath The exact same issue here too, It wowks fine and dandy on the test server using ng serve, but when I tri to build for production, it eventually builds and right after that I get that error. 

WHAAAAAAAAAA -> My build just succeded, the only thing I did was that I tried several other options, like making a new app from scratch just to test the cron editor. I started to get frustraited so I went back and tried again. Boom, magick, it builds. I am kinda happy, because I have spent the last 2 days modifying this editor to use @angular/material2 instead of bootstrap and now it finally builds.

**Comment by sainathraoghanate** [comment] 2018-06-18 09:35
I am also getting the same issue as @henrikcs 
Can anyone help me out to close this issue?

ERROR in : 'cron-editor' is not a known element:
1. If 'cron-editor' is an Angular component, then verify that it is part of this module.
2. If 'cron-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
("-editor [(cron)]="cronExpression" [options]="cronOptions"></cron-editor> -->
                      [ERROR ->]<cron-editor >Cron here...</cron-editor>
                    </div>
                    <!-- Genera")

**Comment by sainathraoghanate** [comment] 2018-06-19 05:37
After a long struggle, it worked for me.
I removed the cron-edito package from the package.json.
I created on cron folder with the required files and added the necessary files to it.
Then I build for the production. It succeeded.

**Comment by ubiqs** [comment] 2018-06-19 11:24
Hi can you share the files on GitHub?

Thanks

**Comment by claudiuconstantin** [comment] 2018-11-20 08:32
Hey everyone, there's a new major version of this library, please test it and see if the issues above still occur. Thank you so much for your support!

**Comment by henrikcs** [comment] 2018-11-24 00:26
This issue seems to be resolved. With the new version of this module, I can build my project without any problems.

**Comment by claudiuconstantin** [comment] 2018-11-28 15:55
Glad to hear that, @henrikcs! I'll leave this open for a few days for any additional feedback, then I'll consider it Resolved

**Closed as completed** 2019-06-19 07:48 UTC
Labels: bug

**Comment by Saitejas1997** [comment] 2021-01-06 12:32
How to have minutes tab as default?
